checks:
  doNotAutoAddDefaults: true
  include:
    - "dangling-horizontalpodautoscaler"
    - "dangling-ingress"
    - "dangling-service"
    - "deprecated-service-account-field"
    - "docker-sock"
    - "duplicate-env-var"
    - "env-var-secret"
    - "invalid-target-ports"
    - "latest-tag"
    - "privileged-ports"
